# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/information_sampling_task_modeling',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/information_sampling_task_modeling',
                'lib_path': 'information_sampling_task_modeling'},
  'syms': { 'information_sampling_task_modeling.core': { 'information_sampling_task_modeling.core.foo': ( 'core.html#foo',
                                                                                                          'information_sampling_task_modeling/core.py')}}}
